import PageHeader from '@/components/PageHeader';

export default function AboutPage() {
  const terms = [
    {
      term: "Solar Energy",
      definition: "Energy from the sun's radiation, captured using photovoltaic (PV) panels or solar thermal mirrors.",
      category: "Renewable"
    },
    {
      term: "Wind Energy",
      definition: "Energy harvested from the kinetic energy of moving air using wind turbines.",
      category: "Renewable"
    },
    {
      term: "Hydropower",
      definition: "Electricity generated by using the energy of flowing water, typically from dams or river systems.",
      category: "Renewable"
    },
    {
      term: "Other Renewables",
      definition: "Includes geothermal energy (heat from the Earth), bioenergy (burning organic material), and wave/tidal energy.",
      category: "Renewable"
    },
    {
      term: "Nuclear Power",
      definition: "Energy released from the nucleus of atoms, typically through fission. While low-carbon, it is generally categorized separately from 'renewables' due to the finite supply of uranium.",
      category: "Low-Carbon"
    },
    {
      term: "Coal, Oil, & Gas",
      definition: "Fossil fuels formed from ancient organic matter. These are the primary sources of carbon emissions in energy production.",
      category: "Fossil Fuel"
    },
    {
      term: "Total Generation (TWh)",
      definition: "The total amount of electricity produced by a country in a year, measured in Terawatt-hours.",
      category: "Metric"
    },
    {
      term: "CO₂ Intensity (g/kWh)",
      definition: "A measure of how much carbon dioxide is emitted for every kilowatt-hour of electricity produced. Lower values indicate 'cleaner' energy grids.",
      category: "Metric"
    }
  ];

  return (
    <div className="space-y-10 max-w-4xl mx-auto">
      <PageHeader
        title="About TerraWatt"
        description="Learn about our data sources, the terminology we use, and the methodology behind our energy transition analysis."
      />

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">Data Sources</h2>
        <div className="prose prose-invert text-slate-300">
          <p>
            TerraWatt relies on high-quality, publicly available energy and emissions datasets to provide accurate visualizations and simulations. Our primary sources include:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              <strong>Our World in Data (OWID):</strong> Global energy mix and emissions data provided by the University of Oxford.
            </li>
            <li>
              <strong>Ember Energy:</strong> An independent energy think tank providing open-access data on the global electricity transition.
            </li>
            <li>
              <strong>IPCC Emissions Factors:</strong> Approximate lifecycle carbon intensity values for different energy sources used in our simulator.
            </li>
          </ul>
        </div>
      </section>

      <section className="space-y-6">
        <h2 className="text-2xl font-bold text-white">Methodology</h2>
        <div className="bg-slate-800/50 border border-slate-700 rounded-xl p-6 space-y-4">
          <div>
            <h3 className="text-green-400 font-semibold mb-1">Renewable % Calculation</h3>
            <p className="text-slate-300 text-sm">
              The "Renewable %" shown on our global map and charts is calculated as the sum of percentages from four key categories:
              <br />
              <code className="bg-slate-900 px-2 py-1 rounded mt-2 inline-block text-green-500">
                Renewable % = Hydro % + Wind % + Solar % + Other Renewables %
              </code>
            </p>
          </div>
          <div>
            <h3 className="text-blue-400 font-semibold mb-1">Grid Simulation</h3>
            <p className="text-slate-300 text-sm">
              Our simulator uses "Weighted Average Carbon Intensity" to predict changes. When you shift the energy mix, we apply standardized emissions factors (e.g., 820g CO₂/kWh for Coal vs 11g/kWh for Wind) to the new proportions to estimate the impact on total national emissions.
            </p>
          </div>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-bold text-white">Terminology</h2>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {terms.map((item) => (
            <div key={item.term} className="p-4 bg-slate-900 border border-slate-800 rounded-lg hover:border-slate-700 transition-colors">
              <div className="flex justify-between items-start mb-2">
                <h4 className="font-bold text-slate-100">{item.term}</h4>
                <span className={`text-[10px] uppercase tracking-wider px-2 py-0.5 rounded border ${
                  item.category === 'Renewable' ? 'border-green-500/50 text-green-400' :
                  item.category === 'Fossil Fuel' ? 'border-red-500/50 text-red-400' :
                  'border-blue-500/50 text-blue-400'
                }`}>
                  {item.category}
                </span>
              </div>
              <p className="text-sm text-slate-400 leading-relaxed">{item.definition}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="pt-10 pb-6 border-t border-slate-800 text-center text-slate-500 text-sm">
        <p>Last updated: February 2026. This project is for educational purposes.</p>
      </footer>
    </div>
  );
}
